# fly.toml app configuration file created for nmm-agentic-system
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nmm-agentic-system'
primary_region = 'iad' # Example region, change as needed

[build]
  builder = "paketobuildpacks/builder:base"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

# This section mounts the persistent volume to the /data directory in the container.
# This is where we will store our checkpoints.sqlite3 file.
[mounts]
  source="langgraph_data"
  destination="/app/data"